### ISSUE TITLE
Conflict Between Nuke's Python Environment and System Python Packages

### ISSUE THREAD

**Issue by faithcure** [Theo-SAMINADIN-td/NukeSamurai#1]
Nuke 14.1v3 uses Python 3.9 internally. However, the system-installed Python 3.10's NumPy and OpenCV packages are being loaded in Nuke's environment, causing module incompatibility and C-extension errors.

When loading OpenCV (cv2), the following error occurs:
`ImportError: No module named 'numpy.core._multiarray_umath'`
Nuke attempts to use the Python 3.10 site-packages path, leading to a version mismatch issue.

Also, Nuke 15 uses python 3.9 how you solve it?

**Comment by jmon2097** [comment]
I get the same error as yours in Nuke 14. Seems that the required version of numpy isn't compatible with python 3.9

Nuke 15.0 + use Python 3.10.6.
Switching to Nuke 15, I get a different error (Windows):
```
Traceback (most recent call last):
  File "C:/Nuke_Py3/gizmo/NukeSamurai/menu.py", line 4, in <module>
    from scripts.nuke_samurai import CreateSamuraiNode, UpdatePath, GenerateMask, BoundingBox, InputInfos
  File "C:\Program Files\Nuke15.0v4\pythonextensions\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Nuke_Py3/gizmo/NukeSamurai\scripts\nuke_samurai.py", line 6, in <module>
    import torch
  File "C:\Program Files\Nuke15.0v4\pythonextensions\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Program Files/Python310/Lib/site-packages\torch\__init__.py", line 143, in <module>
    raise err
OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Program Files/Python310/Lib/site-packages\torch\lib\shm.dll" or one of its dependencies.
```

This page mentions to add other paths to the PATH environment variable:
https://stackoverflow.com/questions/74594256/pytorch-error-loading-lib-site-packages-torch-lib-shm-dll-or-one-of-its-depen
but adding the suggested "Python\Library\bin" to the environment doesn't solve the issue. 
Also adding this path to the init.py doesn't solve the issue:
`nuke.pluginAddPath("C:/Program Files/Python310/Library/bin", addToSysPath=True)`

I read that this has been tested with Ubuntu, so there may be additional steps to include the missing dependencies in Windows ?

**Comment by Theo-SAMINADIN-td** [comment]
Hi! Nuke 14 is using Python 3.9 which is incompatible with the current version of SAMURAI. However, Nuke 15 does support Python 3.10!

I haven't tested or deploy this on Windows. I would recommend you to either :

- Try to install SAMURAI using [WSL ](https://learn.microsoft.com/en-us/windows/wsl/install) with Ubuntu as recommended on [SAM2 Github](https://github.com/facebookresearch/sam2/blob/main/INSTALL.md) 
- Installing SAMURAI following [this guide](https://www.youtube.com/watch?v=MIUxiLjoA1g), but it implies some changes in the installation.

Third-Party Library Versions for Nuke 14.1
https://learn.foundry.com/nuke/14.1/content/misc/studio_third_party_libraries-141.html

Third-Party Library Versions for Nuke 15
https://learn.foundry.com/nuke/15.0/content/misc/studio_third_party_libraries-150.html?cshid=Dissolve
