### ISSUE TITLE
how can i implement this extension in windows 

### ISSUE THREAD

**Issue by Ajnash-ibn-umer** [Theo-SAMINADIN-td/NukeSamurai#2]

**Comment by Theo-SAMINADIN-td** [comment]
SAM2 [Github](https://github.com/facebookresearch/sam2/blob/main/INSTALL.md) recommends to use [WSL ](https://learn.microsoft.com/en-us/windows/wsl/install) with Ubuntu.

Someone has found a way to install SAM2 on Windows, you could, in the same way install SAMURAI, but of course it implies changes in the installation. 
Here's the video : https://www.youtube.com/watch?v=MIUxiLjoA1g.
